[2021-12-06 16:08:09,548] [INFO] [base._load_session] -> No session loaded
[2021-12-06 16:08:09,551] [INFO] [base._start_message] -> 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: TcpTarget
                 UI: WebInterface listening on 127.0.0.1:26001
                 Log: ./kittylogs/kitty_20211206-160807.log

                 Total possible mutation count: 1000
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
[2021-12-06 16:08:09,552] [INFO] [base.start] -> Performing environment test
[2021-12-06 16:08:11,581] [ERROR] [tcp.pre_test] -> Error: Traceback (most recent call last):
  File "D:\windowsSoftware\Anaconda\envs\S7comm\lib\site-packages\katnip\targets\tcp.py", line 57, in pre_test
    sock.connect((self.host, self.port))
  File "D:\windowsSoftware\Anaconda\envs\S7comm\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

[2021-12-06 16:08:11,581] [ERROR] [tcp.pre_test] -> Failed to connect to target server, retrying...
